// Smoke test for the patched official workspace client bundle
// (lib/client.js, generated by lib/build.mjs): executes it in Node with a
// minimal DOM + services stub so syntax/typo/apply errors are caught before
// the browser loads it. Rendering happens inside the slot framework, so apply
// only needs locale/slots/workspaces/sessions stubs.
import { createRequire } from "node:module"
import { readFileSync, globSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"
import { homedir } from "node:os"

// Resolve react from the install that owns this checkout: the profile's own
// node_modules first (DSH_HOME-aware — hardcoding ~/.dsh read the wrong install
// on an isolated instance), then the npx cache the CLI bootstraps from.
const dshHome = process.env.DSH_HOME || join(homedir(), ".dsh")
const reactCandidates = [
  join(dshHome, "profiles", "web", "package.json"),
  join(dshHome, "profiles", "package.json"),
  ...globSync(join(homedir(), ".npm", "_npx", "*", "node_modules", "react", "package.json")),
]
let React = null
for (const candidate of reactCandidates) {
  try {
    React = createRequire(candidate)("react")
    break
  } catch {
    // try the next install
  }
}
if (React === null) throw new Error("cannot resolve react from any dsh install")

let factory
const fakeWindow = {
  __ModuleLoader__: {
    load: ({ id, factory: f }) => {
      if (id !== "@lim324/dsh-worktree-panel") throw new Error("unexpected bundle id: " + id)
      factory = f
    },
  },
}

const code = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "..", "lib", "client.js"), "utf8")
// The bundle touches document only inside __wtpEnsureCss (called from a
// component hook) and the CSS module injector, which is guarded by
// `typeof document !== "undefined"`; render paths are not exercised here.
new Function("window", code)(fakeWindow)

if (!factory) throw new Error("bundle did not register a factory")

const primitivesStub = new Proxy(
  {},
  {
    get: (target, prop) => {
      if (prop === Symbol.toStringTag) return "Module"
      // Components reference icons/primitives lazily at render time only.
      return (...args) => (typeof args[0] === "string" ? args[0] : "stub")
    },
  },
)

const mod = factory((name) => {
  if (name === "react") return React
  if (name === "react/jsx-runtime") {
    return { jsx: React.createElement, jsxs: React.createElement, Fragment: React.Fragment }
  }
  // 0.1.5-rc.1 deleted @deepseek-ai/dsh-client-runtime; the bundle now takes
  // Service from cordis and defineStore from dsh-client-store. Both are served
  // by the web shell's seed table in the browser, so they only need stubs here.
  if (name === "@deepseek-ai/cordis") return { Service: class Service { constructor(c) { this.ctx = c } } }
  if (name === "@deepseek-ai/dsh-client-store") return { defineStore: (spec) => ({ ...spec }) }
  if (name === "@deepseek-ai/dsh-client-ui-primitives") return primitivesStub
  throw new Error("unexpected require: " + name)
})

if (typeof mod.apply !== "function") throw new Error("client bundle exports no apply")
if (!Array.isArray(mod.inject)) throw new Error("client bundle exports no inject list")

// In 0.1.5-rc.1 both halves read their dependencies through `ctx.get(name)`, and
// `workspaces`/`sessions` expose a `list` SNAPSHOT STORE (getSnapshot/subscribe)
// rather than a bare array. Mirror that shape; `get` and the ambient properties
// resolve to the same objects so either access style works.
const workspacesList = {
  getSnapshot: () => ({ items: [], archivedSessionIds: [], current: undefined }),
  subscribe: () => () => {},
}
const sessionsList = {
  getSnapshot: () => ({ ids: [], byId: {}, current: undefined, phase: "ready" }),
  subscribe: () => () => {},
}
const services = {
  connection: { hostDescription: "test-host" },
  // the panel's augmentation registers an input-trigger source; the effect
  // callback returns its disposer.
  inputTriggers: { registerSource: () => () => {} },
  workspaces: {
    list: workspacesList,
    startSession: () => {},
    rename: async () => {},
    delete: async () => {},
    insertBefore: async () => {},
    archiveSession: async () => {},
    insertSessionBefore: async () => {},
    create: async () => ({}),
  },
  sessions: {
    list: sessionsList,
    search: async () => ({ ok: true, value: { items: [] } }),
    searchResultLimit: 50,
    binding: () => undefined,
    clear: async () => {},
    create: async () => "child",
    fork: async () => "child",
    open: () => {},
  },
}

const registrations = []
const ctx = {
  get: (name) => services[name],
  ...services,
  layout: {},
  remote: { directoryPicker: { pick: async () => undefined, available: () => false }, query: {} },
  locale: { register: () => {} },
  slots: {
    entries: () => [],
    subscribe: () => () => {},
    inject: (name, cb) => {
      registrations.push({ name, registered: cb() })
    },
    register: (opts, Component) => ({ opts, Component }),
    provideRoot: () => {},
  },
  effect: (fn) => {
    const dispose = fn()
    return () => {
      try {
        dispose?.()
      } catch {
        /* ignore */
      }
    }
  },
}

mod.apply(ctx) // official apply registers effects/slots via ctx; returns undefined by design

const slotNames = registrations.map((r) => r.name).join(",")
if (!slotNames.includes("sidebar.workspaces")) throw new Error("sidebar.workspaces slot not registered")
if (!slotNames.includes("conversation.hero.workspace")) throw new Error("hero workspace slot not registered")

console.log(
  "client smoke test OK: patched official bundle factory ran, apply registered slots [" + slotNames + "]",
)
